version: "3"

services:
    mongodb:
        image: mongo:latest
        volumes:
            - ./mongo-init/:/docker-entrypoint-initdb.d
            - mongo-data:/data/db
        environment: 
            - MONGO_INITDB_DATABASE=model-phone-system
        ports:
            - 6000:27017

volumes:
    mongo-data: