version: "3"

services:
    server:
        build: ./server-api
        volumes:
            - ./server-api:/app
            - /app/node_modules
        ports:
            - 5000:5000
        environment:
            - PORT=5000
            - DB_CONN=mongodb://mongodb:27017/model-phone-system
            - SESSION_PWD=supercalifragilisticexpialodocious
        
    mongodb:
        image: mongo:latest
        volumes:
            - ./mongo-init/:/docker-entrypoint-initdb.d
            - mongo-data:/data/db
        environment: 
            - MONGO_INITDB_DATABASE=model-phone-system

volumes:
    mongo-data: