version: "3"

services:
    server:
        build: ./server-api
        volumes:
            - ./server-api:/app
            - /app/node_modules
        ports:
            - 5000:5000
        environment:
            - PORT=5000
            - DB_CONN=mongodb://mongodb:27017/model-phone-system
            - REDIS_CONN=redis://redis:6379
            - SESSION_PWD=supercalifragilisticexpialodocious

    client:
        build: ./react-client
        volumes:
            - ./react-client:/app
            - /app/node_modules
        ports:
            - 3000:3000
        environment:
            - HTTPS=true
            - SSL_KEY_FILE=./ssl/key.pem
            - SSL_CRT_FILE=./ssl/certificate.pem
            - PROXY_SERVER=https://server:5000
        stdin_open: true
    
    # phone_0001:
        # build: ./phone-emulator
        # command: <phone account ID> https://server:5000
        # volumes:
            # - ./phone-emulator:/phone-emulator
            # - /phone-emulator/__pycache__
            # - /tmp/.X11-unix:/tmp/.X11-unix:rw
        # environment:
            # - DISPLAY=$DISPLAY
        
    mongodb:
        image: mongo:latest
        volumes:
            - ./mongo-init/:/docker-entrypoint-initdb.d
            - mongo-data:/data/db
        environment: 
            - MONGO_INITDB_DATABASE=model-phone-system
    
    redis:
        image: redis:6-alpine
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes: 
            - ./redis:/usr/local/etc/redis
            - redis-data:/data


volumes:
    mongo-data:
    redis-data: